-- =========================================================================
-- CEFI E-Commerce: Supabase Security Lock-down (RLS & Storage Policies)
-- Copy and paste this script into your Supabase Dashboard -> SQL Editor -> Run
--
-- Model: the browser (anon key, or a signed-in customer's token) may only
-- READ the catalogue. Every write goes through the Express API, which checks
-- the admin role and talks to Supabase with the SERVICE-ROLE key — that key
-- bypasses RLS, so no write policies are needed (or wanted) here.
--
-- BEFORE RUNNING: set SUPABASE_SERVICE_ROLE_KEY on the backend (Vercel ->
-- Project -> Settings -> Environment Variables) and redeploy. If the backend
-- is still on the anon key, admin saves will fail once this script runs.
--
-- Safe to re-run.
-- =========================================================================

